### ISSUE TITLE
IFA/ACE mortars doesn't work ?

### ISSUE THREAD

**Issue by Wait4Code** [bux/IFA3_ACE_COMPAT#20]
Hi,

It seems that all mortar of IFA mod (and with your ACE compat mod) don't work. I can assemble it, but I can't reload it (or maybe I do it in the wrong way ?)... When I try without ACE, it works so it let me think that ACE (and the compat) is the problem origin...

By advance, thank you.

And sorry for my bad english which is not my mother tongue.

**Comment by ElTyranos** [comment]
You have to place ACE Mk6 module and enable ammo handling

**Comment by Wait4Code** [comment]
Ok thank you it works
