### ISSUE TITLE
Flamethrower shoots 90° downwards due to ACE advanced ballistics

### ISSUE THREAD

**Issue by JasperRab** [bux/IFA3_ACE_COMPAT#23]
While using,

```
class ACE_Settings {
         class ace_advanced_ballistics_enabled {
		value = 1;
		typeName = "BOOL";
		force = 1;
	};
};
```

Meaning enabling advanced ballistics from ACE the Flamethrower shoots 90° downwards from the gun.

Used mods:
ace
cba_a3
cup_terrains_complete
ifa3_ace_compat
ifa3_aio_lite

Video:
http://i.imgur.com/LD9s2Ek.gifv

Test mission:
[FlamethrowerTest.VR.zip](https://github.com/bux/IFA3_ACE_COMPAT/files/1235228/FlamethrowerTest.VR.zip)

Log file (if needed):
[arma3_x64_2017-08-18_19-50-47.zip](https://github.com/bux/IFA3_ACE_COMPAT/files/1235230/arma3_x64_2017-08-18_19-50-47.zip)

**Comment by kju** [comment]
should be fixed IFA3 v27
