### ISSUE TITLE
GrWr34 ACE mortar elevation

### ISSUE THREAD

**Issue by shifty98** [bux/IFA3_ACE_COMPAT#24]
My issue is that i cannout shot from specific range ...it was tested on my maps and with same result, only walkaround i managed to do is using sandbags to put mortar on for raising the elevation ...but issue was in when you would get out it would shot you either in sky or smack you hard on ground and Knock you out ...here is pictures of my Mk6 setting and how much Max elevation was shown without round loaded, and how much it was with loaded round (can be see load and not loaded in top right corner) this testing was done or fairly flat ground (neuville right by church), iam trying to solve this beucase for us the mortar is then combat ineffectif from ..+- 500m if we are on flat ground 
![107410_20170827232911_1](https://user-images.githubusercontent.com/31392972/29754198-bf998874-8b80-11e7-8eb9-82f1c1e8e48a.png)
![107410_20170827232934_1](https://user-images.githubusercontent.com/31392972/29754199-bf9ae43a-8b80-11e7-81f2-915187002230.png)
![107410_20170827233136_1](https://user-images.githubusercontent.com/31392972/29754200-bf9cc20a-8b80-11e7-91a5-860d00383bec.png)
![107410_20170827233155_1](https://user-images.githubusercontent.com/31392972/29754201-bf9da242-8b80-11e7-9170-c1321cd56a48.png)
![107410_20170827233203_1](https://user-images.githubusercontent.com/31392972/29754202-bfa09574-8b80-11e7-9724-6bde96f2fa5a.png)

**Comment by ElTyranos** [comment]
Should be fixed in next version.

**Comment by Wiket123** [comment]
Still is not fixed!
