### ISSUE TITLE
LIB_SIGN_MINEN_mag no longer exist in IFA3

### ISSUE THREAD

**Issue by Catsy73** [bux/IFA3_ACE_COMPAT#25]
"LIB_SIGN_MINEN_mag" no longer exist in IFA3 but it's call at there lines :
https://github.com/bux/IFA3_ACE_COMPAT/blob/2fa47deeb6814cfd6089c0ded5a63d40f5f70329/addons/main/CfgVehicles.hpp#L652
https://github.com/bux/IFA3_ACE_COMPAT/blob/2fa47deeb6814cfd6089c0ded5a63d40f5f70329/addons/main/CfgVehicles.hpp#L721

It's cause crash on dedicated server when there crates are use.

**Comment by ElTyranos** [comment]
https://github.com/bux/IFA3_ACE_COMPAT/commit/ba6e904e1c0a5f5bea6b67b052b4088bd602744a
