### ISSUE TITLE
ACE rearm module doesn't work properly

### ISSUE THREAD

**Issue by ghost** [bux/IFA3_ACE_COMPAT#27]
While rearming vehicles with the current module settings you would rearm 400 rounds for the tank rounds or use all the ammo in the ammo storage instead one by one

Rearm Module
Rearm Amount: Amount based on caliber
Ammunition Supply: Only Specific Magazine

**Comment by ElTyranos** [comment]
Should be fixed in v31 since we reviewed cost of all weapons, please confirm.
