### ISSUE TITLE
Fuel trucks are empty

### ISSUE THREAD

**Issue by ElTyranos** [bux/IFA3_ACE_COMPAT#3]

**Comment by ghost** [comment]
If this is still an issue I can look into it.

**Comment by Drofseh** [comment]
I gave the code a quick look and I think all the fuel trucks have the right entries.
https://github.com/bux/IFA3_ACE_COMPAT/blob/master/addons/main/CfgVehicles.hpp#L554

`MACRO_REFUEL_ACTIONS` and `ace_refuel_fuelCargo` are the ones to look for.
