### ISSUE TITLE
IFA Hand Grenades break ACE3 Select Frag/NonFrag keys.

### ISSUE THREAD

**Issue by Drofseh** [bux/IFA3_ACE_COMPAT#30]
Mods:
```
CBA v3.5
ACE3 v3.12.1
IFA3 Lite Preview v26
Version 26.0
```
**Description:**
- If any IFA grenade is in the player's inventory the ACE3 `Select Frag Grenade` and `Select Non-Frag Grenade` cease to cycle between grenades properly, always selecting a single type of frag or non-frag grenade respectively.
* See this [video](https://www.youtube.com/watch?v=48np3pGo1_E)

**Steps to reproduce:**
- Go into Virtual Arsenal and import this loadout:
```
comment "Remove existing items";
removeAllWeapons this;
removeAllItems this;
removeAllAssignedItems this;
removeUniform this;
removeVest this;
removeBackpack this;
removeHeadgear this;
removeGoggles this;

comment "Add containers";
this addBackpack "B_LIB_GER_SapperBackpack_empty";
this addItemToBackpack "LIB_nb39";
this addItemToBackpack "LIB_f1";
this addItemToBackpack "MiniGrenade";
this addItemToBackpack "SmokeShellGreen";
this addItemToBackpack "SmokeShellBlue";
this addItemToBackpack "SmokeShellOrange";
this addItemToBackpack "ACE_M14";
this addItemToBackpack "ACE_M84";
for "_i" from 1 to 3 do {this addItemToBackpack "30Rnd_9x21_Mag";};

comment "Add weapons";
this addWeapon "hgun_PDW2000_F";
```
- Try the loadout
- Press the `Select Frag Grenade` key several times, it will continuously select the vanilla RGN Grenade
- Press the `Select Non-Frag Grenade` key several times, it will continuously select the vanilla Green Smoke.
- Note that the selected grenade in the vanilla UI also doesn't not change, staying on an IFA grenade.
- Drop the IFA F1 `LIB_f1` and IFA Nebelhandgranate 39 `LIB_nb39` grenades on the ground.
- Pressing the `Select Frag Grenade` key will now properly cycle between the vanilla RGN Grenade and the ACE3 M84 grenade, as well as displaying the selected grenade in the vanilla UI.
- Pressing the `Select Non-Frag Grenade` key will now properly cycle between all vanilla smoke grenades and the ACE AN-M14 grenade, as well as displaying the selected grenade in the vanilla UI.
- Pick up either IFA grenade, both keys fail to cycle properly (except in vanilla UI but only until an IFA grenade is selected).

**Comment by kju** [comment]
do you know who to talk to from ACE team best about this by chance?

**Comment by bux** [comment]
@commy2

**Comment by Drofseh** [comment]
I did not know who, so thanks bux.

**Comment by kju** [comment]
commy2 - Today at 7:48 PM
 
Reading the issue it's about these keybinds from ACE:
> Press the Select Frag Grenade key several times, it will continuously select the vanilla RGN Grenade
> Press the Select Non-Frag Grenade key several times, it will continuously select the vanilla Green Smoke.

But that would also be fixed by making separate muzzles for the custom smokes instead of reusing the vanilla ones.

**Comment by kju** [comment]
possibly fixed in IFA3 v27

**Comment by kju** [comment]
@Drofseh can you please verify

**Comment by Drofseh** [comment]
@kju it seems good to me!
