### ISSUE TITLE
Cannot use rearm vehicles to configure pylons on other vehicles

### ISSUE THREAD

**Issue by zharf** [bux/IFA3_ACE_COMPAT#34]
I think this is due to missing ace_rearm_defaultSupply in vehicles?

**Comment by zharf** [comment]
Worked around the IFA ACE compat mod limitations in mission code

**Comment by zharf** [comment]
didn't actually mean to close this... anyway, I worked around it in mission code but it would still be nice to be fixed in here

**Comment by ElTyranos** [comment]
maybe you can provide the said mission code ?

**Comment by zharf** [comment]
https://github.com/zharf/57_ww2_lib/blob/master/scripts/client/init_client.sqf#L79

it's pretty much the same as ACE pylons code (https://github.com/acemod/ACE3/blob/master/addons/pylons/XEH_postInit.sqf#L4 ) with the addition of checking for LIB_OpelBlitz_Ammo nearby.

I'm pretty sure this could be fixed by adding ace_rearm_defaultSupply for the ammo vehicles

**Comment by ElTyranos** [comment]
should be fixed, please confirm.
