### ISSUE TITLE
Panzerfaust 60 (IFA3) problem

### ISSUE THREAD

**Issue by CmndrFello** [bux/IFA3_ACE_COMPAT#35]
i have encountered a bug while using the IFA3 ACE Compatibility patch.
If you take the IFA3 Panzerfaust 60
and shoot it, it will turn into a Panzerfaust 30 (used)
(without this mod theres a way to reload the launcher, but with it, because it turns it into a Panzerfaust 30 used , you can't reload, and it has a weird view teleport when doing it)(edited)
even though, when shooting the Panzerfaust 30 (IFA3) it does not turn into a used version, only FOW Panzerfausts turn into used versions. so i'm quite confused by this.

**Comment by ElTyranos** [comment]
Technically you are not supposed to be able to reload a panzerfaust, but indeed the model change is an issue, will fix.
