### ISSUE TITLE
Unable to start game with the IFA3 Compat

### ISSUE THREAD

**Issue by 111Insats** [bux/IFA3_ACE_COMPAT#9]
http://prnt.sc/ci8cxz (Error message)
https://gist.github.com/111Insats/a2668e3f94574f0032c112df2f45d4ae (RPT)

Used mods:
CBA 3.0.0
TFAR 0.9.8
IFA3LITE
Iron Front in Arma 3 ACE compatibility

**Comment by ElTyranos** [comment]
You need to launch with ACE3 and therefore last CBA version.
https://github.com/CBATeam/CBA_A3
https://github.com/acemod/ACE3
